const tutorialsData = [
  {
    id: 0,
    title: 'How to turn on your computer',
    author: 'Rick',
    content: `Many people may have trouble turning on their computer. Maybe you don’t know how to turn on your computer, but don’t worry, today, I’ll teach you how to turn on your computer.

    First, you usually need to press the button that turns on your computer. Then, your computer should be turned on.`,
    likes: 1000,
    comments: 2,
    bookmarks: 100,
    tags: ['Computer', 'Hardware', 'Beginner'],
    community: 'Computer',
  },
  {
    id: 1,
    title: 'How to turn off your computer',
    author: 'Rick',
    content: `Many people may have trouble turning off their computer. Maybe you don’t know how to turn off your computer, but don’t worry, today, I’ll teach you how to turn off your computer.

    First, you usually need to press the button that turns off your computer. Then, your computer should be turned off.`,
    likes: 999,
    comments: 2,
    bookmarks: 99,
    tags: ['Computer', 'Hardware', 'Beginner'],
    community: 'Computer',
  },
  {
    id: 2,
    title: 'Basic Algebra Concepts',
    author: 'Charlie',
    content: 'Learn the fundamental concepts of algebra, including variables, equations, and functions.',
    likes: 200,
    comments: 25,
    bookmarks: 90,
    tags: ['Math', 'Algebra'],
    community: 'Math',
  },
  {
    id: 3,
    title: 'Calculus for Beginners',
    author: 'Dave',
    content: 'An introduction to calculus, focusing on derivatives and integrals.',
    likes: 180,
    comments: 22,
    bookmarks: 85,
    tags: ['Math', 'Calculus'],
    community: 'Math',
  },
  {
    id: 4,
    title: 'Basics of Quantum Mechanics',
    author: 'Eve',
    content: 'Understand the fundamental principles of quantum mechanics and its applications.',
    likes: 220,
    comments: 30,
    bookmarks: 95,
    tags: ['Physics', 'Quantum'],
    community: 'Physics',
  },
  {
    id: 5,
    title: 'Classical Mechanics Explained',
    author: 'Frank',
    content: 'A comprehensive guide to classical mechanics, covering Newton\'s laws and motion.',
    likes: 210,
    comments: 28,
    bookmarks: 88,
    tags: ['Physics', 'Classical'],
    community: 'Physics',
  },
  {
    id: 6,
    title: 'Top 10 Games of 2024',
    author: 'Grace',
    content: 'A review of the top 10 games released in 2024, including gameplay and graphics analysis.',
    likes: 300,
    comments: 50,
    bookmarks: 120,
    tags: ['Gaming', 'Reviews'],
    community: 'Gaming',
  },
  {
    id: 7,
    title: 'Building a Gaming PC',
    author: 'Hank',
    content: 'Step-by-step guide to building your own gaming PC from scratch.',
    likes: 250,
    comments: 35,
    bookmarks: 110,
    tags: ['Gaming', 'PC'],
    community: 'Gaming',
  },
  {
    id: 8,
    title: 'Minecraft Survival Guide',
    author: 'Ivy',
    content: 'Tips and tricks for surviving and thriving in Minecraft.',
    likes: 350,
    comments: 60,
    bookmarks: 140,
    tags: ['Minecraft', 'Survival'],
    community: 'Minecraft',
  },
  {
    id: 9,
    title: 'Minecraft Redstone Engineering',
    author: 'Jack',
    content: 'Learn how to use redstone in Minecraft to create complex machines and contraptions.',
    likes: 320,
    comments: 55,
    bookmarks: 130,
    tags: ['Minecraft', 'Redstone'],
    community: 'Minecraft',
  },
  {
    id: 10,
    title: 'Easy Pasta Recipes',
    author: 'Kate',
    content: 'Delicious and easy-to-make pasta recipes for quick meals.',
    likes: 280,
    comments: 40,
    bookmarks: 115,
    tags: ['Cooking', 'Pasta'],
    community: 'Cooking',
  },
  {
    id: 11,
    title: 'Baking Bread at Home',
    author: 'Leo',
    content: 'Step-by-step instructions for baking homemade bread.',
    likes: 260,
    comments: 38,
    bookmarks: 110,
    tags: ['Cooking', 'Baking'],
    community: 'Cooking',
  },
  {
    id: 12,
    title: 'Writing Fiction: Tips and Tricks',
    author: 'Mia',
    content: 'Improve your fiction writing with these essential tips and tricks.',
    likes: 270,
    comments: 42,
    bookmarks: 120,
    tags: ['Writing', 'Fiction'],
    community: 'Writing',
  },
  {
    id: 13,
    title: 'How to Write a Blog Post',
    author: 'Nina',
    content: 'A guide to writing engaging and effective blog posts.',
    likes: 230,
    comments: 32,
    bookmarks: 100,
    tags: ['Writing', 'Blogging'],
    community: 'Writing',
  },
  {
    id: 14,
    title: 'JavaScript for Beginners',
    author: 'Oscar',
    content: 'Learn the basics of JavaScript programming.',
    likes: 310,
    comments: 45,
    bookmarks: 125,
    tags: ['Programming', 'JavaScript'],
    community: 'Programming',
  },
  {
    id: 15,
    title: 'Python Data Analysis',
    author: 'Paul',
    content: 'An introduction to data analysis using Python.',
    likes: 290,
    comments: 40,
    bookmarks: 120,
    tags: ['Programming', 'Python'],
    community: 'Programming',
  },
  {
    id: 16,
    title: 'Creating Effective Tutorials',
    author: 'Quinn',
    content: 'Tips and strategies for creating tutorials that engage and educate.',
    likes: 240,
    comments: 35,
    bookmarks: 110,
    tags: ['Tutorial', 'Education'],
    community: 'Tutorial',
  },
  {
    id: 17,
    title: 'Using Videos in Tutorials',
    author: 'Rita',
    content: 'Learn how to incorporate videos into your tutorials for better engagement.',
    likes: 220,
    comments: 33,
    bookmarks: 105,
    tags: ['Tutorial', 'Videos'],
    community: 'Tutorial',
  },
  {
    id: 18,
    title: 'Organizing Your Workspace',
    author: 'Steve',
    content: 'Tips for keeping your workspace organized and productive.',
    likes: 270,
    comments: 39,
    bookmarks: 115,
    tags: ['Organization', 'Productivity'],
    community: 'Organization',
  },
  {
    id: 19,
    title: 'Digital Organization Tools',
    author: 'Tina',
    content: 'A review of the best digital tools for staying organized.',
    likes: 250,
    comments: 36,
    bookmarks: 110,
    tags: ['Organization', 'Tools'],
    community: 'Organization',
  },
  {
    id: 20,
    title: 'Fishing for Beginners',
    author: 'Uma',
    content: 'An introduction to fishing, including equipment and techniques.',
    likes: 260,
    comments: 37,
    bookmarks: 112,
    tags: ['Fishing', 'Beginners'],
    community: 'Fishing',
  },
  {
    id: 21,
    title: 'Advanced Fishing Techniques',
    author: 'Vic',
    content: 'Learn advanced fishing techniques to catch more fish.',
    likes: 240,
    comments: 34,
    bookmarks: 108,
    tags: ['Fishing', 'Advanced'],
    community: 'Fishing',
  },
  {
    id: 22,
    title: 'Building Your Own PC',
    author: 'Wendy',
    content: 'A guide to building your own computer from scratch.',
    likes: 330,
    comments: 52,
    bookmarks: 135,
    tags: ['Computer', 'Hardware'],
    community: 'Computer',
  },
  {
    id: 23,
    title: 'Computer Security Basics',
    author: 'Xander',
    content: 'Learn the basics of computer security and how to protect your data.',
    likes: 320,
    comments: 50,
    bookmarks: 130,
    tags: ['Computer', 'Security'],
    community: 'Computer',
  },
  {
    id: 24,
    title: 'Analyzing Shakespearean Sonnets',
    author: 'Alice',
    content: 'Explore the intricacies of Shakespearean sonnets and learn how to analyze them effectively.',
    likes: 150,
    comments: 20,
    bookmarks: 75,
    tags: ['Literature', 'Poetry'],
    community: 'English',
  },
  {
    id: 25,
    title: 'Understanding Modern Literature',
    author: 'Bob',
    content: 'A brief overview of modern literature and its significant movements.',
    likes: 100,
    comments: 15,
    bookmarks: 50,
    tags: ['Literature', 'Modern'],
    community: 'English',
  },
];

export default tutorialsData;
